create table if not exists app_users (
  id text primary key,
  email text not null unique,
  password_hash text not null,
  role text not null default 'viewer' check (role in ('admin', 'viewer')),
  created_at timestamptz not null default now()
);

create table if not exists profiles (
  id text primary key,
  email text not null default '',
  role text not null default 'viewer' check (role in ('admin', 'viewer'))
);

create table if not exists colors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  rate numeric not null default 0,
  color_type text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists recipes (
  id bigint generated by default as identity primary key,
  recipe_no text not null unique,
  color_name text not null default '',
  recipe_master_name text not null default '',
  than_count numeric not null default 0,
  hex_code text not null default 'N/A',
  dyes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists programs (
  id bigint generated by default as identity primary key,
  program_no integer not null,
  program_name text not null default '',
  status text not null default 'Pending',
  program_date date not null default current_date,
  required_thans numeric not null default 0,
  stock_deducted boolean not null default false,
  selected_recipe_numbers text[] not null default '{}',
  recipe_snapshot jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  action_type text not null,
  section_name text not null,
  item_name text not null default '',
  old_value jsonb,
  new_value jsonb,
  user_email text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists recipe_versions (
  id bigint generated by default as identity primary key,
  recipe_id text not null default '',
  recipe_no text not null default '',
  color_name text not null default '',
  recipe_master_name text not null default '',
  snapshot jsonb not null default '{}'::jsonb,
  saved_by text not null default '',
  action_type text not null default 'update',
  created_at timestamptz not null default now()
);

create table if not exists process_houses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  phone text not null default '',
  gst text not null default '',
  default_rate numeric not null default 0,
  address text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists chemical_stock_purchases (
  id bigint generated by default as identity primary key,
  chemical_name text not null,
  purchased_qty_grams numeric not null default 0,
  unit text not null default 'grams',
  purchase_date date not null default current_date,
  supplier text not null default '',
  rate_per_kg numeric not null default 0,
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists chemical_stock_ledger (
  id bigint generated by default as identity primary key,
  chemical_name text not null,
  entry_type text not null default 'adjustment',
  qty_delta_grams numeric not null default 0,
  program_id bigint,
  program_no text not null default '',
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists program_stock_usage (
  id bigint generated by default as identity primary key,
  program_id bigint,
  program_no text not null default '',
  program_name text not null default '',
  program_date date,
  chemical_name text not null,
  quantity_used_grams numeric not null default 0,
  before_stock_grams numeric not null default 0,
  after_stock_grams numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists price_change_logs (
  id bigint generated by default as identity primary key,
  chemical_name text not null,
  old_price numeric not null default 0,
  new_price numeric not null default 0,
  updated_by text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_colors_name on colors (name);
create index if not exists idx_recipes_recipe_no on recipes (recipe_no);
create index if not exists idx_programs_created_at on programs (created_at);
create index if not exists idx_stock_ledger_name on chemical_stock_ledger (chemical_name);
create index if not exists idx_program_stock_usage_program on program_stock_usage (program_no);
