create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('admin', 'viewer'))
);

alter table public.profiles enable row level security;
alter table public.colors enable row level security;
alter table public.recipes enable row level security;

alter table public.colors
add column if not exists color_type text not null default '';

update public.colors
set color_type = 'COTTON'
where upper(name) in (
  'BLACK E',
  'BOURDEX BW',
  'BROWN MR',
  'GOLDEN YELLOW HER',
  'GREEN B',
  'MAROON R',
  'NAVY BLUE RX',
  'ORANGE BRO',
  'RED HE3B',
  'RED HE8B',
  'SCARLET 4BS',
  'SKY BLUE FF',
  'TURQUOISE BLUE H5G',
  'VOILET BB',
  'YELLOW 5 GLL',
  'YELLOW HE68'
);

update public.colors
set color_type = 'POLYSTER'
where upper(name) in (
  'BLACK 2RC',
  'BLACK EMRD',
  'BLACK RX-EX CONC',
  'BLUE 2RX',
  'BLUE ER',
  'BRILL BLUE DBR CONC',
  'BRILL BLUE GSL 400%',
  'BRILL BLUE SR',
  'BRILL BLUE X BRSL',
  'BRILL RED 6B',
  'BRILL RED BS',
  'BRILL RED F3BL',
  'BROWN 3REL N',
  'DARK RED 2B',
  'GOLDEN YELLOW 2GNN',
  'LIQUID BLACK SER',
  'LUMINOUS PINK 5BN',
  'LUMINOUS RED G',
  'LUMINOUS YELLOW 10GN',
  'NAVY BLUE 3G 200%',
  'ORANGE RL',
  'RED VIOLET FBL 200%',
  'RUBINE 5BH CONC',
  'SCARLET CRR',
  'VIOLET 3R',
  'WHITE R',
  'YELLOW 7GE',
  'YELLOW BROWN',
  'YELLOW M7G'
);

create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  program_no integer not null,
  program_name text not null default '',
  program_date date not null,
  created_at timestamptz not null default now(),
  selected_recipe_numbers text[] not null default '{}',
  recipe_snapshot jsonb not null default '[]'::jsonb
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  action_type text not null,
  section_name text not null,
  item_name text not null default '',
  old_value jsonb,
  new_value jsonb,
  user_email text not null default '',
  created_at timestamptz not null default now()
);

alter table public.programs
add column if not exists program_name text not null default '';

alter table public.programs enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "profiles can read own role" on public.profiles;
drop policy if exists "admins can manage profiles" on public.profiles;
drop policy if exists "authenticated users can read colors" on public.colors;
drop policy if exists "allow public select colors" on public.colors;
drop policy if exists "allow public insert colors" on public.colors;
drop policy if exists "allow public update colors" on public.colors;
drop policy if exists "allow public delete colors" on public.colors;
drop policy if exists "admins can insert colors" on public.colors;
drop policy if exists "admins can update colors" on public.colors;
drop policy if exists "admins can delete colors" on public.colors;
drop policy if exists "authenticated users can read recipes" on public.recipes;
drop policy if exists "allow public select recipes" on public.recipes;
drop policy if exists "allow public insert recipes" on public.recipes;
drop policy if exists "allow public update recipes" on public.recipes;
drop policy if exists "allow public delete recipes" on public.recipes;
drop policy if exists "admins can insert recipes" on public.recipes;
drop policy if exists "admins can update recipes" on public.recipes;
drop policy if exists "admins can delete recipes" on public.recipes;
drop policy if exists "authenticated users can read programs" on public.programs;
drop policy if exists "admins can insert programs" on public.programs;
drop policy if exists "admins can update programs" on public.programs;
drop policy if exists "admins can delete programs" on public.programs;
drop policy if exists "admins can read audit logs" on public.audit_logs;
drop policy if exists "admins can insert audit logs" on public.audit_logs;

create policy "profiles can read own role"
on public.profiles
for select
to authenticated
using (id = auth.uid());

create policy "admins can manage profiles"
on public.profiles
for all
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "authenticated users can read colors"
on public.colors
for select
to authenticated
using (true);

create policy "admins can insert colors"
on public.colors
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can update colors"
on public.colors
for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can delete colors"
on public.colors
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "authenticated users can read recipes"
on public.recipes
for select
to authenticated
using (true);

create policy "admins can insert recipes"
on public.recipes
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can update recipes"
on public.recipes
for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can delete recipes"
on public.recipes
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "authenticated users can read programs"
on public.programs
for select
to authenticated
using (true);

create policy "admins can insert programs"
on public.programs
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can update programs"
on public.programs
for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can delete programs"
on public.programs
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can read audit logs"
on public.audit_logs
for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can insert audit logs"
on public.audit_logs
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

-- After running the policies, add one row per user:
-- insert into public.profiles (id, role) values ('USER_UUID_HERE', 'admin');
-- insert into public.profiles (id, role) values ('USER_UUID_HERE', 'viewer');
