create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('admin', 'viewer'))
);

alter table public.profiles enable row level security;
alter table public.colors enable row level security;
alter table public.recipes enable row level security;

alter table public.colors
add column if not exists color_type text not null default '';

alter table public.recipes
add column if not exists created_at timestamptz not null default now();

alter table public.recipes
add column if not exists recipe_master_name text not null default '';

notify pgrst, 'reload schema';

update public.colors
set color_type = 'COTTON'
where upper(name) in (
  'BLACK E',
  'BOURDEX BW',
  'BROWN MR',
  'GOLDEN YELLOW HER',
  'GREEN B',
  'MAROON R',
  'NAVY BLUE RX',
  'ORANGE BRO',
  'RED HE3B',
  'RED HE8B',
  'SCARLET 4BS',
  'SKY BLUE FF',
  'TURQUOISE BLUE H5G',
  'VOILET BB',
  'YELLOW 5 GLL',
  'YELLOW HE68'
);

update public.colors
set color_type = 'POLYSTER'
where upper(name) in (
  'BLACK 2RC',
  'BLACK EMRD',
  'BLACK RX-EX CONC',
  'BLUE 2RX',
  'BLUE ER',
  'BRILL BLUE DBR CONC',
  'BRILL BLUE GSL 400%',
  'BRILL BLUE SR',
  'BRILL BLUE X BRSL',
  'BRILL RED 6B',
  'BRILL RED BS',
  'BRILL RED F3BL',
  'BROWN 3REL N',
  'DARK RED 2B',
  'GOLDEN YELLOW 2GNN',
  'LIQUID BLACK SER',
  'LUMINOUS PINK 5BN',
  'LUMINOUS RED G',
  'LUMINOUS YELLOW 10GN',
  'NAVY BLUE 3G 200%',
  'ORANGE RL',
  'RED VIOLET FBL 200%',
  'RUBINE 5BH CONC',
  'SCARLET CRR',
  'VIOLET 3R',
  'WHITE R',
  'YELLOW 7GE',
  'YELLOW BROWN',
  'YELLOW M7G'
);

create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  program_no integer not null,
  program_name text not null default '',
  program_date date not null,
  created_at timestamptz not null default now(),
  selected_recipe_numbers text[] not null default '{}',
  recipe_snapshot jsonb not null default '[]'::jsonb
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  action_type text not null,
  section_name text not null,
  item_name text not null default '',
  old_value jsonb,
  new_value jsonb,
  user_email text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.recipe_versions (
  id bigint generated by default as identity primary key,
  recipe_id text not null default '',
  recipe_no text not null default '',
  color_name text not null default '',
  snapshot jsonb not null default '{}'::jsonb,
  saved_by text not null default '',
  action_type text not null default 'update',
  created_at timestamptz not null default now()
);

alter table public.recipe_versions
add column if not exists recipe_master_name text not null default '';

create table if not exists public.process_houses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  phone text not null default '',
  gst text not null default '',
  default_rate numeric not null default 0,
  address text not null default '',
  created_at timestamptz not null default now()
);

alter table public.recipe_versions
alter column recipe_id type text using recipe_id::text;

alter table public.programs
add column if not exists program_name text not null default '';

alter table public.programs
add column if not exists status text not null default 'Pending';

alter table public.programs
add column if not exists required_thans numeric not null default 0;

alter table public.programs
add column if not exists stock_deducted boolean not null default false;

create table if not exists public.chemical_stock_purchases (
  id bigint generated by default as identity primary key,
  chemical_name text not null,
  purchased_qty_grams numeric not null default 0,
  unit text not null default 'grams',
  purchase_date date not null default current_date,
  supplier text not null default '',
  rate_per_kg numeric not null default 0,
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.chemical_stock_ledger (
  id bigint generated by default as identity primary key,
  chemical_name text not null,
  entry_type text not null default 'adjustment',
  qty_delta_grams numeric not null default 0,
  program_id bigint,
  program_no text not null default '',
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.program_stock_usage (
  id bigint generated by default as identity primary key,
  program_id bigint,
  program_no text not null default '',
  program_name text not null default '',
  program_date date,
  chemical_name text not null,
  quantity_used_grams numeric not null default 0,
  before_stock_grams numeric not null default 0,
  after_stock_grams numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.price_change_logs (
  id bigint generated by default as identity primary key,
  chemical_name text not null,
  old_price numeric not null default 0,
  new_price numeric not null default 0,
  updated_by text not null default '',
  created_at timestamptz not null default now()
);

notify pgrst, 'reload schema';

alter table public.programs enable row level security;
alter table public.audit_logs enable row level security;
alter table public.recipe_versions enable row level security;
alter table public.process_houses enable row level security;
alter table public.chemical_stock_purchases enable row level security;
alter table public.chemical_stock_ledger enable row level security;
alter table public.program_stock_usage enable row level security;
alter table public.price_change_logs enable row level security;

grant select on public.process_houses to authenticated;
grant insert, update, delete on public.process_houses to authenticated;
grant select on public.chemical_stock_purchases to authenticated;
grant insert, update, delete on public.chemical_stock_purchases to authenticated;
grant select on public.chemical_stock_ledger to authenticated;
grant insert, update, delete on public.chemical_stock_ledger to authenticated;
grant select on public.program_stock_usage to authenticated;
grant insert, update, delete on public.program_stock_usage to authenticated;
grant select on public.price_change_logs to authenticated;
grant insert, update, delete on public.price_change_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "profiles can read own role" on public.profiles;
drop policy if exists "admins can manage profiles" on public.profiles;
drop policy if exists "authenticated users can read colors" on public.colors;
drop policy if exists "allow public select colors" on public.colors;
drop policy if exists "allow public insert colors" on public.colors;
drop policy if exists "allow public update colors" on public.colors;
drop policy if exists "allow public delete colors" on public.colors;
drop policy if exists "admins can insert colors" on public.colors;
drop policy if exists "admins can update colors" on public.colors;
drop policy if exists "admins can delete colors" on public.colors;
drop policy if exists "authenticated users can read recipes" on public.recipes;
drop policy if exists "allow public select recipes" on public.recipes;
drop policy if exists "allow public insert recipes" on public.recipes;
drop policy if exists "allow public update recipes" on public.recipes;
drop policy if exists "allow public delete recipes" on public.recipes;
drop policy if exists "admins can insert recipes" on public.recipes;
drop policy if exists "admins can update recipes" on public.recipes;
drop policy if exists "admins can delete recipes" on public.recipes;
drop policy if exists "authenticated users can read programs" on public.programs;
drop policy if exists "admins can insert programs" on public.programs;
drop policy if exists "admins can update programs" on public.programs;
drop policy if exists "admins can delete programs" on public.programs;
drop policy if exists "admins can read audit logs" on public.audit_logs;
drop policy if exists "admins can insert audit logs" on public.audit_logs;
drop policy if exists "admins can read recipe versions" on public.recipe_versions;
drop policy if exists "admins can insert recipe versions" on public.recipe_versions;
drop policy if exists "authenticated users can read process houses" on public.process_houses;
drop policy if exists "admins can insert process houses" on public.process_houses;
drop policy if exists "admins can update process houses" on public.process_houses;
drop policy if exists "admins can delete process houses" on public.process_houses;
drop policy if exists "authenticated users can read stock purchases" on public.chemical_stock_purchases;
drop policy if exists "admins can insert stock purchases" on public.chemical_stock_purchases;
drop policy if exists "admins can update stock purchases" on public.chemical_stock_purchases;
drop policy if exists "admins can delete stock purchases" on public.chemical_stock_purchases;
drop policy if exists "authenticated users can read stock ledger" on public.chemical_stock_ledger;
drop policy if exists "admins can insert stock ledger" on public.chemical_stock_ledger;
drop policy if exists "admins can update stock ledger" on public.chemical_stock_ledger;
drop policy if exists "admins can delete stock ledger" on public.chemical_stock_ledger;
drop policy if exists "authenticated users can read program stock usage" on public.program_stock_usage;
drop policy if exists "admins can insert program stock usage" on public.program_stock_usage;
drop policy if exists "admins can update program stock usage" on public.program_stock_usage;
drop policy if exists "admins can delete program stock usage" on public.program_stock_usage;
drop policy if exists "admins can read price change logs" on public.price_change_logs;
drop policy if exists "admins can insert price change logs" on public.price_change_logs;
drop policy if exists "admins can update price change logs" on public.price_change_logs;
drop policy if exists "admins can delete price change logs" on public.price_change_logs;

create policy "profiles can read own role"
on public.profiles
for select
to authenticated
using (id = auth.uid());

create policy "admins can manage profiles"
on public.profiles
for all
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "authenticated users can read colors"
on public.colors
for select
to authenticated
using (true);

create policy "admins can insert colors"
on public.colors
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can update colors"
on public.colors
for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can delete colors"
on public.colors
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "authenticated users can read recipes"
on public.recipes
for select
to authenticated
using (true);

create policy "admins can insert recipes"
on public.recipes
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can update recipes"
on public.recipes
for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can delete recipes"
on public.recipes
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "authenticated users can read programs"
on public.programs
for select
to authenticated
using (true);

create policy "admins can insert programs"
on public.programs
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can update programs"
on public.programs
for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can delete programs"
on public.programs
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can read audit logs"
on public.audit_logs
for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can insert audit logs"
on public.audit_logs
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can read recipe versions"
on public.recipe_versions
for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can insert recipe versions"
on public.recipe_versions
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "authenticated users can read process houses"
on public.process_houses
for select
to authenticated
using (true);

notify pgrst, 'reload schema';

create policy "admins can insert process houses"
on public.process_houses
for insert
to authenticated
with check (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can update process houses"
on public.process_houses
for update
to authenticated
using (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
)
with check (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "admins can delete process houses"
on public.process_houses
for delete
to authenticated
using (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "authenticated users can read stock purchases"
on public.chemical_stock_purchases
for select
to authenticated
using (true);

create policy "admins can insert stock purchases"
on public.chemical_stock_purchases
for insert
to authenticated
with check (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "admins can update stock purchases"
on public.chemical_stock_purchases
for update
to authenticated
using (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
)
with check (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "admins can delete stock purchases"
on public.chemical_stock_purchases
for delete
to authenticated
using (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "authenticated users can read stock ledger"
on public.chemical_stock_ledger
for select
to authenticated
using (true);

create policy "admins can insert stock ledger"
on public.chemical_stock_ledger
for insert
to authenticated
with check (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "admins can update stock ledger"
on public.chemical_stock_ledger
for update
to authenticated
using (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
)
with check (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "admins can delete stock ledger"
on public.chemical_stock_ledger
for delete
to authenticated
using (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "authenticated users can read program stock usage"
on public.program_stock_usage
for select
to authenticated
using (true);

create policy "admins can insert program stock usage"
on public.program_stock_usage
for insert
to authenticated
with check (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "admins can update program stock usage"
on public.program_stock_usage
for update
to authenticated
using (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
)
with check (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "admins can delete program stock usage"
on public.program_stock_usage
for delete
to authenticated
using (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "admins can read price change logs"
on public.price_change_logs
for select
to authenticated
using (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "admins can insert price change logs"
on public.price_change_logs
for insert
to authenticated
with check (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "admins can update price change logs"
on public.price_change_logs
for update
to authenticated
using (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
)
with check (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "admins can delete price change logs"
on public.price_change_logs
for delete
to authenticated
using (
  auth.uid() = '2d40e8ad-d9dd-4043-8750-9c09cfc029e6'::uuid
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

notify pgrst, 'reload schema';

-- After running the policies, add one row per user:
-- insert into public.profiles (id, role) values ('USER_UUID_HERE', 'admin');
-- insert into public.profiles (id, role) values ('USER_UUID_HERE', 'viewer');
